import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/style/globals.css";

import IsMobileProvider from "@/context/ui/isMobile";
import I18nProvider from "@/i18n/provider";

import Header from "@/components/Header";
import MobileMenu from "@/components/mobileMenu";

const Satoshi = localFont({
  src: [
    {
      path: "../../public/fonts/Satoshi.ttf",
    },
    {
      path: "../../public/fonts/Satoshi-Italic.ttf",
      style: "italic",
    }
  ],
  variable: "--font-satoshi",
  display: "swap",
});

const Merriweather = localFont({
  src: [
    {
      path: "../../public/fonts/Merriweather.ttf",
    },
    {
      path: "../../public/fonts/Merriweather-Italic.ttf",
      style: "italic",
    }
  ],
  variable: "--font-merriweather",
  display: "swap",
});

const Fraunces = localFont({
  src: [
    {
      path: "../../public/fonts/Fraunces.ttf",
    },
    {
      path: "../../public/fonts/Fraunces-Italic.ttf",
      style: "italic",
    }
  ],
  variable: "--font-fraunces",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Merriweather.variable} ${Satoshi.className} ${Fraunces.variable} antialiased`}
      >
        <I18nProvider>
          <IsMobileProvider>
            <Header />
            <MobileMenu />
            <main className="max-w-screen-lg w-full inset-0 mx-auto px-6 md:px-4 lg:px-8 pt-8">
              {children}
            </main>
          </IsMobileProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
