import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "@/style/globals.css";

import IsMobileProvider from "@/context/ui/isMobile";

import Header from "@/components/Header";
import MobileMenu from "@/components/mobileMenu";


const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} antialiased`}
      >
        <IsMobileProvider>
          <Header />
          <MobileMenu />
          <main className="max-w-screen-lg w-full inset-0 mx-auto px-6 md:px-4 lg:px-8 pt-8">
            {children}
          </main>
        </IsMobileProvider>
      </body>
    </html>
  );
}
